from pydantic import BaseModel, Field
from typing import Optional
from fastapi import UploadFile, File


class ChatRequest(BaseModel):
    messages: Optional[str] = Field(..., description="The message to be processed by the chat model.")
    lang: Optional[str] = Field(default="nl", description="Language code (nl, fr, en, es) for the response.")


class ChatResponse(BaseModel):
    response: str = Field(..., description="The response generated by the chat model.")


class UploadDocumentResponse(BaseModel):
    document_id: str = Field(..., description="The ID of the uploaded document.")
    filename: str = Field(..., description="The name of the uploaded document.")
    path: str = Field(..., description="The file path where the document is stored.")
    status: str = Field(..., description="The status of the document upload.")
